### ISSUE TITLE
New main menu song

### ISSUE THREAD

**Issue by Aryan14** [iosoccer/iosoccer-game#491]
Had a poll on this 2-3 months ago and around 65% wanted a new one.
I know it's not an easy thing to find one that is good enough and copyright free.
Remove the current one at least?

**Comment by Thinge** [comment]
Not sure there's anything to gain from removing the current one. I think it's fine, although if someone finds a better one, then obviously that's great.

**Comment by Aryan14** [comment]
For now keeping current. Will be debatable after release.
