### ISSUE TITLE
Remove single keeper

### ISSUE THREAD

**Issue by Aryan14** [iosoccer/iosoccer-game#503]
Since this feature got implemented it does got us a lot of games. However it also reduced the amount of 'natural' keepers that we have to a point that only 1 player still wants to keep regularly.

Reason for this are:
- You have double responsibility to not concede goals.
- You can't focus on 1 side of the team.
- New and even old players will feel even more bad about keeping because they will concede twice as much goals than when keeping on 1 side only. They might not even admit it but it's the mental part.
- Disrespectful towards keepers by not valuing the position.

I am sure that there is more reasons why single keeper is a terrible thing for IOS.
Majority probably still want to keep single keeper because it does give you a lot matches than without it. However I am looking for the keeper interest part. Keeper right now is more a mercenary position than really an actual one.

Rather have less matches but always 2 human keepers. Sooner or later single keeper feature has to go.

**Comment by Thinge** [comment]
I still don't know on this one. I think it's a nice-to-have feature as a last resort, but I agree that the culture surrounding it can be problematic. Until a time when the community is bigger, I don't think it can be removed, and when that time comes I think it will still be a discussion rather than a definite removal.

**Comment by romdi** [comment]
I'm closing this, because the problem should solve itself for online play with a bigger community and for LANs it can be useful to have the option for solo keeper if you don't have enough players locally otherwise.
