### ISSUE TITLE
Change player country setting from ISO 3166 to FIFA country codes

### ISSUE THREAD

**Issue by eoinl** [iosoccer/iosoccer-game#510]
Scotland, Wales, Northern Ireland and England at the least are missing from the country option

**Comment by Aryan14** [comment]
As long the proposed second Scottisch referendum hasn't taken place and with the outcome that Scotland is going to be fully independent. Scotland will remain part of the United Kingdom flag.

**Comment by Aryan14** [comment]
We will move to FIFA country codes list. So Scotland will be available once done.

**Comment by romdi** [comment]
Done.
